// Auto-generated by update-marketplace.js — 2026-03-09T01:26:28.947Z
// Paste this into src/components/NFTMarketplace.tsx

export const IPFS_BADGES = [
  {
    "tokenId": 1,
    "name": "B2S Badge #1",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidcb3rtrzzosvv44fekxwkyeubdjgxr3lwz6ou6euw5khy2xxrx7u",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibifuvgauuuaa3tzyuuujvbf73gmcd3qibjn2v3ukmmgc5u2xudti"
  },
  {
    "tokenId": 3,
    "name": "B2S Badge #3",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreif7zex7vvgdnmqshydn2vscv6rp5zhodoj63uqvo7v3x2anieoxs4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifnwiyad3qnj5rukbk2sd4cdr4n6tqyxz6byd4cxbpazeuiwfviza"
  },
  {
    "tokenId": 2,
    "name": "B2S Badge #2",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicqoasepmmpeeee7e7d5buxjwb24ej4rjnfgfd3eh35wsvy5ck6n4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiakd6arl6xqwgpdtdilil6y4x47m7dqflk6o2obfena3our6m5dqm"
  },
  {
    "tokenId": 6,
    "name": "B2S Badge #6",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreie5w7iy5jbesf77bm3nkjpo5v72qd4ov6b4caygyubjbxtodjt45a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihr25m7u7axs3ouq4cgx2pvj3nsftdpqwe4omrqn3n3nfgmcuvg5y"
  },
  {
    "tokenId": 5,
    "name": "B2S Badge #5",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicnulhxix3h74oqppynycvrvrlptwh4yiswh6q44mbipqrpap4zsa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiah5ekjsxfd4abkfk356czwxb27ryibz2aryxaj3ac5bq37k5ap4e"
  },
  {
    "tokenId": 4,
    "name": "B2S Badge #4",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig3c7fk6ikzmlotwczxvb4ibvvfnw35664tgps37tzc5vlg7v4jrm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifuhm22ucubsoqpe2zgjfqjcgud5lvhpr2topcgvyly6pfgzpjgwe"
  },
  {
    "tokenId": 9,
    "name": "B2S Badge #9",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig4qz2djntqsedxuqkwsspdoev7jqpll77obahyqdmon6qncvkoda",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifkmt6fqd5tecvas3tez5d6364uokwp5jkpggzkyurupi4urwn6nm"
  },
  {
    "tokenId": 7,
    "name": "B2S Badge #7",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiglcty7wcodzoywig36sz7fz2yreerxbfjovm2hotss6huzjgbd4y",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicaoczuaoqlupkhrqotvx64uzmfmonrf6cnfioeain3zwayl7hl4y"
  },
  {
    "tokenId": 8,
    "name": "B2S Badge #8",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreielavblm4mstjfhgq4etaxwbjgvzz7dw4k7ccoe574fgryxmnhlqi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib3ok4kzwkabm5yqv3eq4b6c43ezkauaznq5edllivcrd5g7g2ria"
  },
  {
    "tokenId": 11,
    "name": "B2S Badge #11",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiekkbuhz236ob45nwvfn4lskdohshxeiwpegcelxvvtq4czierdru",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiejaxtxtzu2lxf6rzhjjte6wk4svdqk2lyi3ujsuncuvsigyjj6oi"
  },
  {
    "tokenId": 12,
    "name": "B2S Badge #12",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibdy2cqw27ee6a2wocu7djargjhy224mn3kvktobcvhju6w4jvlna",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibuximozgcwjldvarzdl53bqznrri6qvs5im7scgnuhv4bz54ii7y"
  },
  {
    "tokenId": 10,
    "name": "B2S Badge #10",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifawo5bqzolxipljmu74n2w3ggodugzeoozz4pokkcw6zlapn7x4m",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiedocfvax2j57c4545wnodh2qvogpit4fep66mgeyzxcflci4fihe"
  },
  {
    "tokenId": 14,
    "name": "B2S Badge #14",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreie7csb7ocepxgw4f7d37fovht4oombzh4tgsv2num2thqjfcm7djm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibcbakzgkyqfdf2mq33shskdqwcskchyf7lw25w4q5ciieez77oze"
  },
  {
    "tokenId": 13,
    "name": "B2S Badge #13",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreid4jromul6tkh6vptrdtv45qtsjl2ch6khpdfr6724japlqjbllha",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreianiyujsmmy5ljlosgql5utqxu5smok6ywzvvmi5kn556l6t2qepu"
  },
  {
    "tokenId": 15,
    "name": "B2S Badge #15",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreickben2vkbtoibf2okjfbvjmv6rmsjbzckcuxol3cwavtemkug7nm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreig4zx4qgqfaeo2yo332el3gj6uqbxto7i2h54wbnhtvsnauqgelsu"
  },
  {
    "tokenId": 16,
    "name": "B2S Badge #16",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicgzxwecfqalrbgxcy477acz7pcqude6krm5lx5xslblito7cvgli",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihri2mzzejtgjsaqjwos6sbvn4ekax2qjpigdmen5yp56dtn4upq4"
  },
  {
    "tokenId": 18,
    "name": "B2S Badge #18",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiewsyvlttgythjwb2ptdhccgk5ekxeyzsrqougtwwklhmges4aw4i",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibimjjtlltouozj4laiqv6x2xw6rvuns6h56j234qx5ac47m6qibe"
  },
  {
    "tokenId": 17,
    "name": "B2S Badge #17",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicpewodasei5oysclxa4zctufdkjdphxhaf27nyq5h5jnajdrf6fe",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiefcgpfjisjbhsjztkkdswm2sxr6qwhdfhyrzygilvpxdt4yqttei"
  },
  {
    "tokenId": 21,
    "name": "B2S Badge #21",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifpprouwxww4cavbwd7es4ihtwu43j6mqh2dxqnth6g6gvi4niaxe",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibjwixurvp46rdma6e7adoeeyg66msx4pswcks7rrl4ewqo75xgqe"
  },
  {
    "tokenId": 20,
    "name": "B2S Badge #20",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiea5t5cje2azx6kwhsekblybeund34f3fmisnhcsnb2jkxt73524m",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiesr5fdbfdy2ttgqsyukluohn6ecewpaewiox5zaupjxp2n6zswte"
  },
  {
    "tokenId": 19,
    "name": "B2S Badge #19",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihil72smxonift5sc527jlgwekp463ecbnl54w7xtuaboobfv7wdy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib3rke22cdyzw5x3dnnyeptlan54vq6fhaez3bkbh43zxaqyuhoo4"
  },
  {
    "tokenId": 24,
    "name": "B2S Badge #24",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaafbujdwtodjw3u6gjrabqfvaeryx3gcix3lr4qz33uukoxv2uwu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreie2wuciyo22rtjk2nt6awxsxcdsr46nrtii364rb3su5mj7lcwseq"
  },
  {
    "tokenId": 23,
    "name": "B2S Badge #23",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicmkluhvslqv6oovjpk7yjoj3sqhaxj5bzibkh67j2hkkre5dhiue",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigm3w6rn4hwoogvharnnrw352bf46vhqz2b6uwsyd4kfgwbkr576y"
  },
  {
    "tokenId": 22,
    "name": "B2S Badge #22",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidf2dhd26rlarljpfk55ggnytynkv5b62cay7626rxq2vw3wkgqny",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihczwolbu7x3wnwaath55wkvh2sb3vvhvblz54wf234dhcfzrmlia"
  },
  {
    "tokenId": 25,
    "name": "B2S Badge #25",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig6t4fvxax2xf625oqopzgr4su2covx2uc6qo4wywyixzmjjw4cqa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid2tqone4gdaxkezynln6mtixd3vpiqr5km5ci2wgdwof4yti652i"
  },
  {
    "tokenId": 26,
    "name": "B2S Badge #26",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreielbfv3itvxdi2nwfsie7ewe5bqqx2xuacdoh3iycepnip5m5zxdu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieaq4voedsz43j55e4vmk4qfcqqmjjl54byk4ze73ovvxkod45nvq"
  },
  {
    "tokenId": 27,
    "name": "B2S Badge #27",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifzjojdcbr4bffqdhq3i24kyzvpl2v4osb66x4lipobzezx5it7ba",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifd5tni4rygjdp4eziir55h7g3eym6axy6wr3cfrnu5aadijo3wpq"
  },
  {
    "tokenId": 29,
    "name": "B2S Badge #29",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibdoqyhexmisd26k7aelfjv2n5vec2jwf3baoiyzk63qwiozutyem",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid5uouroolp32tg5qsd7rp6kya2hwweita3ttteekulwzezeyo2c4"
  },
  {
    "tokenId": 30,
    "name": "B2S Badge #30",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreih2ni2lzme7yqydjgkkcyly3ukdvxz4sg6nf6j5awwqsbc37eq6ju",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihlfag663lde2kn4zrixexlhqb5srfw47fdzfwgnc5sbjz46q3sii"
  },
  {
    "tokenId": 28,
    "name": "B2S Badge #28",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicv2q5jyfxvnlgzclf3gi7bmtz5cbg3gmawebanqio5bv3b5mcfsi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiccq6qghw2ietvytyz4kylsnhfdem7h4oj5oj34yzn5kecp3sohry"
  },
  {
    "tokenId": 32,
    "name": "B2S Badge #32",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreida7mo5bhsnparxpgpaovzzxcxw3r7ppt3gb6favylqsslqeptmbm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifc7a5zcosmquqfg3jti32azglihlsnv537oef3ho7kpwgcen4xfa"
  },
  {
    "tokenId": 31,
    "name": "B2S Badge #31",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigkkiwwqspobom5qfq2nz4srcakip3y2x5pfstjui43utw4q5y4na",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicozdlf6mllvtzxup5lzmpfntp72vwqyb6p2mmv7e5y2ibfftl3qq"
  },
  {
    "tokenId": 33,
    "name": "B2S Badge #33",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig2jaradv46rf3u5dgu5fhekxlzmaxzdfwnomzacmx6grns2h45m4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreia5zuvdkwtvecnia35p3gjayzm4mqmotr5nkyor5qvnzhuil4aptm"
  },
  {
    "tokenId": 34,
    "name": "B2S Badge #34",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidiqx2urasjbqrptgbdsuypvumcgzpkojydw3rcbrdeeqqgceacq4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifmimmsyp545wuchfp3uh76xnhrghwtlxfcoin3pasgfzn5lg7fjm"
  },
  {
    "tokenId": 35,
    "name": "B2S Badge #35",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreift26hl7qkp4oewaux7zn5zomg3jp4gjixkjeoo5rlm4yztq73dvu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifjyz2h2lrbfhs7hy7orzgssnqteypxxuz6n4jjvtb75ve6desxru"
  },
  {
    "tokenId": 36,
    "name": "B2S Badge #36",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigpdyqej4d6rdmzhk3pe4xspf2nznfczcikor3kbjiq6gvqnxrmxu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigjdscxqvfmexwiszmgfse2opah7j3usuq6dibqjmxaxcjkwtyedq"
  },
  {
    "tokenId": 38,
    "name": "B2S Badge #38",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "legendary",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihsywezp7e2t6q6b34oi75vxnwpeuv6rx2pggtxtlgpvrcuvpguhu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidjvwaats4cpfuiaxcixhxfohd5ytrp3ijtdzolh3pp4t25nqit3y"
  },
  {
    "tokenId": 39,
    "name": "B2S Badge #39",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreielbrddgwobe6vyf4ezedxtd2ij7fdy6eg6ybntddnciygrlzakty",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreictcdz6dmi75umaib3v3s7ztlsovxmmn2aqhl4rtmlkxy7wlx7fra"
  },
  {
    "tokenId": 37,
    "name": "B2S Badge #37",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihcirfc6tyql3gpm5xn5tppgeykrybsy3c7b6d2ycajee5uu54sju",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib33et2vezq7usdmgdwvmqmycmm4iqhtvkctwzzbgltxd2qtcwgzu"
  },
  {
    "tokenId": 40,
    "name": "B2S Badge #40",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreia5qoopgg7gysrhvawcz2bmbvnokt2ufnkhujqofhuvztphy7k3zm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicpp4ji4qtln4yotxeapqe33vkmxkezlfnvnhfxob4nd362galgqe"
  },
  {
    "tokenId": 41,
    "name": "B2S Badge #41",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifyuxge33ycs4sewp6idw3lbaunbteabxaxga65co3nyswxqugznm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihfzpsyuuprbghhomx6ornmc4tux52rqzzhn4pclfknjeb6vlc4pm"
  },
  {
    "tokenId": 42,
    "name": "B2S Badge #42",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihip2exg3jftd2eacprdrik42bu3s75cy7i6ziw56h2yzpdfdxcg4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieglltiigsjvvma72xgkvw5utytld4uksywidx6623ybwm5wcybwm"
  },
  {
    "tokenId": 44,
    "name": "B2S Badge #44",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidakhwb53s4xawmvb436ple5xbwr7tfamr7bqpxcezv3hwksfejqa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid7fysslsvgqb2ifoeus562elboxscq6dzjka7ebj3ku4zs3jcuvq"
  },
  {
    "tokenId": 43,
    "name": "B2S Badge #43",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreib6mdbf2zzozjlpyqfsz4rgp7zlxelj736felo522hnri5rhxmp4a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihdz6nys7na44hasmyzv6ctne5wvintb3iodyixhh5h7haaciixoy"
  },
  {
    "tokenId": 45,
    "name": "B2S Badge #45",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreida7slpqiujd23ykma3hnhkima3fgwjakityjr5huel74spdfqbwq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigtpemjpdbyqsh4odn7zlwaxik66rnlpzzwnavu7sjjzrpkxnkhlm"
  },
  {
    "tokenId": 47,
    "name": "B2S Badge #47",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreia3kqaoov5dwq2q77cdlw7tslgvklgilivujkryuymx3ghbtxj3ci",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib7kvz3xepoi6iqq7geydcser7vjklj2og5l35eykmto5yerte6pm"
  },
  {
    "tokenId": 48,
    "name": "B2S Badge #48",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigcotybj2dx7hb4gvamfmmro6oebds4kylkohmt7q2a7tkncqlhei",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifitosuyzrshyxps74esvlcmlbjpnobxdnrbjiqocptb53swolp3e"
  },
  {
    "tokenId": 46,
    "name": "B2S Badge #46",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiegpu4njrqkizfr2ar3bn5rytw6pp3avxm7y6vb6au3hmsju5xr54",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihbfpp3xex7e3jv45ri2a2ropam5gdeh4q7ti4ks53wddwtlnabtm"
  },
  {
    "tokenId": 49,
    "name": "B2S Badge #49",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicwo36phgreu4snvayvnundjximrrpsviwmoq4t7vvudqqwjdaxwy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib7ffb7jdszbudmoukiogglpbyeu4eggfmiddbyca7okyet7lipqy"
  },
  {
    "tokenId": 51,
    "name": "B2S Badge #51",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieukcr2zrlkll7fdfqsmaixgxoyr7sulmmstjmvsn2uqaqe3otfbu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreig6zuomkaqf6gqoxwh6x3zvcfddqcrnwqjqclayd5cbofxxhxecay"
  },
  {
    "tokenId": 50,
    "name": "B2S Badge #50",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiceldv55jbg7e4uf6rky57kbza36gychlfhmms7y6jaxfcjkxdtzi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidy4xkkk2knl2wabqrs3ehf5tpuekrcwju2cazulda4edke2j3mp4"
  },
  {
    "tokenId": 54,
    "name": "B2S Badge #54",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaxlnxflt2spta6aoabi5onos3jlrubmmvjb4zrni4ewgojqi7anq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiept4pjstjh4c4dman3dknvkrxm3nttpseknkge7nwldzrpsnrcuq"
  },
  {
    "tokenId": 53,
    "name": "B2S Badge #53",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig352zaqwmcksypgunl6tyocwpy22nadzk2w5mulc7lyfqcuxzzeu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigjilpj5uqg5jeu5oxoyniqhs4jl4auzvy56n4picxbk6ctnf3kx4"
  },
  {
    "tokenId": 52,
    "name": "B2S Badge #52",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibjh2duowvibchwkx6keojbsie5lrafxlxfubxt2ormxtfqsmzroq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigwz6ux4sizfthwokudcve4loheuwodvarosowbtk6b6hjmeknqai"
  },
  {
    "tokenId": 57,
    "name": "B2S Badge #57",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifocefptyaqa2til367uptzfqxthur5m6bgp4eqrhkxdc5m7f7tee",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreig2g6psmyze3dm477qymvhvzhiqbwtn6oar4y2xtybcad4rmeshui"
  },
  {
    "tokenId": 55,
    "name": "B2S Badge #55",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreickhiklnlgcseqxguqz4l4v25syuyvjgxsorznatenjxvuwoo2axa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigwfcs3qehiqzlpywdzclzkndm3yxwlxsuf4vko2esnl2b762ayda"
  },
  {
    "tokenId": 56,
    "name": "B2S Badge #56",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicr5xzzq6qiypbbclp2d5zn43pks2do7462jgub3yoelltj4araye",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihhbewl27genubv5f2dqff6id64psqgnwhm743zbofolpnyiorfpq"
  },
  {
    "tokenId": 58,
    "name": "B2S Badge #58",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreial2p4iv5kinomoeubr5zew3nykzpqwdxqvjikfcxquilbt2hfse4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidswfkjgqibccqktxz3qnwozgfdihzrwjlboyfk7ifn7obts2vmsa"
  },
  {
    "tokenId": 59,
    "name": "B2S Badge #59",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiasadcwrmjpof5mnqpzmkrqjn7x3hxq37wo72dqkvyp52kyrawesi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicsbejqrl32awlzeslvc75has3hmxi3bv5rcpb5wnreuxxgjhxuru"
  },
  {
    "tokenId": 60,
    "name": "B2S Badge #60",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibjxz3kksirivozhjw355qmqnsxq2vjy6rq4yp3hcqqcjw3injulu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicf3dptzvultmunigmrlw4ti6ixshyefh3hc3g4ntfwbaqwucqehy"
  },
  {
    "tokenId": 62,
    "name": "B2S Badge #62",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibz4g3mlpra5gsrradhh7szy7zbytokbs3ggut5lewzkthbqkpjsu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigqm56dzkhimhws6jnmhz64novle2nugfedslwaageybjlv4pv22q"
  },
  {
    "tokenId": 63,
    "name": "B2S Badge #63",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihg4duzeckarbjrgpcaepmgauvrjkptmxbj6a3sqlys4zy2bczuli",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiemz3vbuhur2nc3hwldfkfhoozz2teh6vovstzh4vicjvuh5jupeu"
  },
  {
    "tokenId": 61,
    "name": "B2S Badge #61",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidjoo5bg6glypdqy5usrgnsnkvgxs22btbimi7rqdzxuknqzpc2ee",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiesqddb3nvgrng3sbe7iskkvs26py3zii5objl7cul6q3eysitxoa"
  },
  {
    "tokenId": 66,
    "name": "B2S Badge #66",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreie26xsjxcy6sgruzp7kh4eua7hw4eq56hl5e27h7kgnufdzf4dnx4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihzyi44zq3p5kuaksacx62vfi5pmswfeidpevb2c2d2r6nimidngm"
  },
  {
    "tokenId": 64,
    "name": "B2S Badge #64",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihf7ousztu2to7hpbm32my2tipoqzdvgefuepiwpjrkpugdexbsja",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifmdc4jnm3v2ve25ucc73qhwfkrgnapovtxktj7x6uvflzmwny5tu"
  },
  {
    "tokenId": 65,
    "name": "B2S Badge #65",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig5mkdf5iczrywtk7jthrc6uueit5ykj2hao2knq72equlqq6ezk4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib5i6lt4eexcnmxxgjcfc7byhehljvbf2mqio2omdsky5f6txkqg4"
  },
  {
    "tokenId": 68,
    "name": "B2S Badge #68",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreievhk5dredlbqjhfaq342qi42m7akhnot274t4itt6favl3ahdoma",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiapmbfbqtssk2lqadacef5i4bslwgwx23olz3qixxgmz5itfmamlm"
  },
  {
    "tokenId": 67,
    "name": "B2S Badge #67",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiblhbi2ozwe2nzdkzx6m5zrsxbve2dtyp52eve2we6r3bnihmlvze",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigjt2nxugyxvaz2mltsfxax4yn7rd3kdky4fy74edpwhihckjpmsi"
  },
  {
    "tokenId": 69,
    "name": "B2S Badge #69",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihihfo6mf2muq45p6y2rwm24rbuvtwld2co5er4hv6wlr4xz2qbtm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifgolbczzrz4szeir4eqqg3hnwhfxayhilsqe7w7laofwof5m5xx4"
  },
  {
    "tokenId": 71,
    "name": "B2S Badge #71",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreia376kq3cklnqylns4fzairasbaqdwqlxqlyab4wp7d23ajcaoy2u",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihcxvwxkgrzuwo7ap7mzokpeaehq6zugvpsrpavcdw627cgtsnp24"
  },
  {
    "tokenId": 72,
    "name": "B2S Badge #72",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreid4h76xvqckkg3foxsoxhk3inesulftbw7bnpjles65y5bicl2fum",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihe2cf4u3y3fhag7fxlmjfyk6dm6luyjh5ri72l42acfiddz7baqi"
  },
  {
    "tokenId": 70,
    "name": "B2S Badge #70",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiffyo74sxtwm56deccyvtdbqokvhjsyc26nge5qkoidsi22an5lpi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiam3i44dh4sssvlahabmaf4gnmjcrif2bzh5kctdat62ig4i2z67q"
  },
  {
    "tokenId": 74,
    "name": "B2S Badge #74",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreic5dm4fbin6vvbppv6v5e7eyun4635g4ju6vvmly5l2vsv3nqrxni",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibfr33pdcik4ej4vfqiigbojrbwvudufayfpn4ppzg4dgjn4muvny"
  },
  {
    "tokenId": 75,
    "name": "B2S Badge #75",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicvjamn52xzmq5bhmv3vbbvpxvvdobxrnjmzdh3b5noronwelp6fm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiedch3y5nxnnzkwa6s6fmoerumyxerycqbjayty2pij3xc5myrufu"
  },
  {
    "tokenId": 73,
    "name": "B2S Badge #73",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigjhbugk5k5l5ipt2jnxj33cnhj2n5knragllxcfzdsbl3oqdt2vu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibmcavzp7k3i4su6ier5p7om5hudvmq4fs5bkxxphzc2znfd2c56i"
  },
  {
    "tokenId": 76,
    "name": "B2S Badge #76",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "legendary",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigaf2lsv2xlvnhweauo3rhgli55gcnk66bakhcoevswapgmnv2lia",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidiuo6fs22ponqe7bwdppidchgldmuz5gk3b7mknfskpfw6ctkh44"
  },
  {
    "tokenId": 77,
    "name": "B2S Badge #77",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreie7tla64wx6myhk5layhfexefptqxrsygpvvwgvq35sfctcsdmozq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigoc6ze6k5yetwyerbbuw4hwvz2cvk53z4rldy3aqcdqhxr6kka4m"
  },
  {
    "tokenId": 78,
    "name": "B2S Badge #78",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifea5tyonrhwq6shrjzt7seczzhzygsqlezfm4o66k6bhffsmruyy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifl7i257yros5p56qu2zju56ppi7qlod2rugtaydrmkz6rdgnwaju"
  },
  {
    "tokenId": 79,
    "name": "B2S Badge #79",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiekslxqwol7iqf6sr6pwkfjf7x7pqfwitu5mfunwuhxnpjtlfjdhu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiftpgrikwn2ippcsm5hypqvniyaa7h25uljl37oql5z6f77hwipbu"
  },
  {
    "tokenId": 80,
    "name": "B2S Badge #80",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigz6thpfhsgahfrvulm4eznf3gttjgbbmj3zsalcq6oqwz73oq5qu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiamkbb2dwkyt5mpt6shqyw6nhml4aath4ofdwldtfickwgjxrybji"
  },
  {
    "tokenId": 81,
    "name": "B2S Badge #81",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihrkktzdcaeuadvizhkcy2aoz6ylcyqupmeim4munfnljx23ksa6q",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidgsowtr4yjo62l5krhjldqpfn2rdzlsyppgvmiqs2z7lrnpmqz3a"
  },
  {
    "tokenId": 83,
    "name": "B2S Badge #83",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieqasmyqgkicupfeyzgzizz4aahb7mg2wsljaelvecy2b5nctby2m",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreichvcm7k2lf6cuiiqqu4lg2qz2tct5biezfrohv2towuwmqa4rjgq"
  },
  {
    "tokenId": 84,
    "name": "B2S Badge #84",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreic3zcqqnmxigwz5rx7d4abphb7qtciibzx34ozlwsyr3jil7kqxem",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigf6t7a7i45fgecgpq567oobga6uqll36dsvmuzm3xn5qvc77goha"
  },
  {
    "tokenId": 82,
    "name": "B2S Badge #82",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigqv4x7uvtclo2fqqy3axlo6bxl3cnmyqcgfqxgevsmvp5duwfrn4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifbmppl3eyfbarj6i35sz7sencroq3ohivstvhb4d43rtk2h4jbey"
  },
  {
    "tokenId": 85,
    "name": "B2S Badge #85",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaxwyojs6hq5pxua7gsgk7x4sxdonfjiium76lqe7fajjfruissoe",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicp64fiezauvckzmyckdq5n4qfciwddivy6tugsqeipclcjw5mz4y"
  },
  {
    "tokenId": 87,
    "name": "B2S Badge #87",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreid3m4qei2rmt54xrfikrhdawexr4epavp7hglm3ve2fagnuy4luxu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid5sckw5kqm3cxuxveryee3ad5iddqocxmvior5atcheg2m76bmfu"
  },
  {
    "tokenId": 86,
    "name": "B2S Badge #86",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifee25465doebzv5c3jdfjscuf7xsrv3yy6qldv3khntie7wqkeru",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieldvvb3vr23pzw7osx7j7r7kur2yj26krurscp7bkp2tyk4zzjkq"
  },
  {
    "tokenId": 89,
    "name": "B2S Badge #89",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieofrp7sik4rhs7lg46kjascmormzcvldan6myrjp5vce4yahen4e",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidbfs4kuzddbli2f374vbekqwobn2ng7cgwyhxyzn2zqwuc6ikkeq"
  },
  {
    "tokenId": 90,
    "name": "B2S Badge #90",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihy6vhocxp6fj2bsdj5fkwf2jl7vz7i2665lbhdrvirsxczs62scq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicg2xbb3oayqyf7avm7xej5vmapviimoufsvmap3owfnlnth6pg5i"
  },
  {
    "tokenId": 88,
    "name": "B2S Badge #88",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibyvcva2lbzddqtrdk2bj2vda7upjamlrsczs3ukoqfa3aqowkz3a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifx5n5zdf23rrpdiayaijfi3ekh56ayd4txakakuhiiulr4mdjkxu"
  },
  {
    "tokenId": 93,
    "name": "B2S Badge #93",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreialzwn75kbv3tb42bcugactycm64toygzehuuqbgxiyayynglzdvm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiegvpqrqltikyfug6f66l3n27o2srgfmxrwlloysk5tsaggtgs7na"
  },
  {
    "tokenId": 92,
    "name": "B2S Badge #92",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiebdy6lqvddhi2sm7vxngrabgg73zewejsbi3ulv5dzr2wxqzjele",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreih3abks26xoygsucrvufw5z5lscghm5iv5h67z6s3wsnnwrsdf6fe"
  },
  {
    "tokenId": 91,
    "name": "B2S Badge #91",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiczw44u7uqkscdff2goti4aw2zttlcb5isz3yrssy2wcmckxjby3a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicyoflb6vq22cdgjoma23lebx3tolo646ru3xgg76bbbsx5rdnemm"
  },
  {
    "tokenId": 96,
    "name": "B2S Badge #96",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihds6qzlxxv7wjnynfdvt3wvzrmr54i6ik3xoa5kkrgfj75r2njc4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicmj3a67ty5y7ki7kb6mrmi24m3s5oe3zb5obnrrsbb7bfz6kqluu"
  },
  {
    "tokenId": 94,
    "name": "B2S Badge #94",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiakuiu4dcfgty2krkhkjykk7zgvjrrlvzmejg4m7mx5hej7c6bekq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaido6ast6ibq2p7i4cbbhmppfls2fqggwhstpkzygdsw5ohrikze"
  },
  {
    "tokenId": 95,
    "name": "B2S Badge #95",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiet7ehdmpzbvpu5yyfztogveck5x3ewhw57jxj6za2yzdlzrruqwy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihuqiozq5njnkx7we5gl24azem7ueojtl3rpljquthjbqzfek4gqe"
  },
  {
    "tokenId": 99,
    "name": "B2S Badge #99",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicdkxtdzv5nn2k4wvyoaav6u46qfjsktxmyh6p6hh2h47ibgunuua",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihxvisvc53ef2mzkmhpi3yu6f64v4dg7osypamukirsuiwloo5woq"
  },
  {
    "tokenId": 98,
    "name": "B2S Badge #98",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihzsxwlunzp7wzzgk6szyn7kg7hkdtbseibnm4hxmnx7ljovsoive",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidqvrocqtol5vveqtdm72batepoonsfgbuqybzc6f6sfki2wnozce"
  },
  {
    "tokenId": 97,
    "name": "B2S Badge #97",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiflcnshmariexgca4v3mlybezum4bu7i2j6w4bonli25notl2uu5y",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihsve2mnvvxx633k5rroahsmtsqduc4i6xapphhsoy72yt43z44zi"
  },
  {
    "tokenId": 101,
    "name": "B2S Badge #101",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreih7cdpf3szhs2om3xj53cps577s73ell4hrfo3qz2i6oizepico2e",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibczd7mdhvay6l7n3hftvr3yae53d5clagvqecuvwmtmrupidckri"
  },
  {
    "tokenId": 100,
    "name": "B2S Badge #100",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifulnzmzdzqpoy2rzbt4uzpsqdvfjktfkz37qoabi45xoii4pm654",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidy3knkackpdd6ldt663qsyk4k4ax5yfwdze2jfspdemg5mhfomle"
  },
  {
    "tokenId": 102,
    "name": "B2S Badge #102",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiep7hs6ujm7tpjp52lwmvadjqy2pm7crtj72zobxpa4b7cy4qkify",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicutq57moujqtodu5cdkgm755l3ap3jajtqtm7ytvfmemz2727isa"
  },
  {
    "tokenId": 103,
    "name": "B2S Badge #103",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigcv5zmmmizf52y3b6eq7nxepkzq2h5elbdhxnu3eaes27vpbn6si",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreie6gwyakcjljicweoo67qrelt2ati7wghfzfyyxvsgyoa2stjli54"
  },
  {
    "tokenId": 104,
    "name": "B2S Badge #104",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibyjmcxhdpyqsokf27cgwitjefyhkcljn7jr23brug7o6pwmy255a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigfngklsk2uwrd6vfeqadpgzkihve4rqu7vboj5eiv2mjiplnl6zm"
  },
  {
    "tokenId": 105,
    "name": "B2S Badge #105",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihxjzrih2vcdu4mfhsiekoo2vthq5e2eictm5pe7fyddgvmihts7q",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiey4h3nicyynkr4rf3rfutqk5xn4wovqu3s7g7hhs3ndshbs7kx74"
  },
  {
    "tokenId": 106,
    "name": "B2S Badge #106",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidk4pnz5i676pqp4w4gl65xpekdr74e4jc2ukrtqacrhilsqadnvq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihvlr7dnyqumnjuwrlbj2w72bizk5u2pjeyrvglu4vna4ekogm72e"
  },
  {
    "tokenId": 108,
    "name": "B2S Badge #108",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifztqivqpnmx7khq75jljelmxojur37bo7h765blrbhzimbbbszdy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaeg7stlwhaiidcwxlhusma72r3ax6vqttmg4pkbxwc4i346k6udy"
  },
  {
    "tokenId": 107,
    "name": "B2S Badge #107",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidtk6fu57p2xssafoqoikuy36ny4f2x2exrrjwynvr5aoviefqevi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibetbkkjr6df4pykbdv37kzc6ysnl6w6wzw7pkuwpsl6fc7zm3lti"
  },
  {
    "tokenId": 109,
    "name": "B2S Badge #109",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig2iy2smfbqtiov6vd7xyquvjd2k7jhr2j3uxxdljurqt45s2wgyi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigndi4aarwenstggl6biqpxkce5qdrx7amfqmprmpvwyp7fdllbvi"
  },
  {
    "tokenId": 111,
    "name": "B2S Badge #111",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreif3iax732prqcsavixt7x6kfauvp4t4aiayhe3w6e4pikezwessye",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieoeaghw4slb2wl5d6bkzs4hbkhp6bgxtu7lwc4qnw6h7mhqoqpje"
  },
  {
    "tokenId": 110,
    "name": "B2S Badge #110",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicmwwyzzklcj2lcpv3d7rjf4t6xw6pbhhux235umgjvbkddbr6nry",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieptk53dhjaf4mphn6devzmnadptwlcxb57q4l2hixmgp4raoindm"
  },
  {
    "tokenId": 113,
    "name": "B2S Badge #113",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig3qs7r6mziikv6hjpj25eaf44rgdqnhrh5pptiseq7nntstbmjwy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifhbcequinlec2neunuzjvjtaae2w32uekiieejxgn76uewinn4zq"
  },
  {
    "tokenId": 112,
    "name": "B2S Badge #112",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicrgngo5iv4kmt2fuknw5rhw4bmmrgc5s6j7cusm4g226wyovfqza",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieerqut2cb3bkxxxrdnngsu3i6kf4br6pmbwlhkrn5vyfcsdinpy4"
  },
  {
    "tokenId": 114,
    "name": "B2S Badge #114",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "legendary",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreianssyh6jdvlbcel27qbjtyjjl224y5h3p2vcy4hl5dpv3wkbhzcq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihvsyxk36wsbhywigdc6m32hjfjfequapwvaosmydlbtfbt7akz3u"
  },
  {
    "tokenId": 117,
    "name": "B2S Badge #117",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaqyd7s5743tkmk5cdcrd67cqhqlz7da7blheszccyhuvi5y2sxre",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidhiycqwmw4vjvu7h5gf6wczapkd4at6yyp34rngufhtd67xutta4"
  },
  {
    "tokenId": 116,
    "name": "B2S Badge #116",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiho47uifloliuk6k2t3ipxzxsqvq2n6xftojxjn2jehdl62u7toi4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieuifgpx64oxfthrdhjm3zrejy2zm5upq6sk2n77izz2pemi5szz4"
  },
  {
    "tokenId": 115,
    "name": "B2S Badge #115",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibzb3pvbbb2yva6eeoaifhu4llzsppetdxjpsll2ct7tgumt5eoq4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibtjlgf7mr3p6hq46tvfiiwerj7iffsppmssxigijye4ice46gvbe"
  },
  {
    "tokenId": 120,
    "name": "B2S Badge #120",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiadzn24sxlgbdy5sdlmymv6lp4waljuza7u7tz5zdr5fnn2vt3suu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidcas62pbcmxwhpp4ohkg4o3znqy7bgmai7jx2uerwugeorgphtna"
  },
  {
    "tokenId": 118,
    "name": "B2S Badge #118",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigsnn6xdtqe2gu34zklc2dop67reqjjvgb5ot7tf3f3cy2kldcscq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidicf3givdh3nycn2yr4exthkkbsc5fkpicehyhny7obgx6desrmu"
  },
  {
    "tokenId": 119,
    "name": "B2S Badge #119",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigjpacyabt6j2tiquuxevyq5za5laehpjnnvibhf4gi23dhwkbsjy",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreie3bul22mcqnpcdxl3pqs5tt5cqdo55t7fc6ja2casxff3txobfri"
  },
  {
    "tokenId": 121,
    "name": "B2S Badge #121",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiangs4b5ul2cebez7aki22chnx5ivc5a7q4euzclp4gcaftz3lgbq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibz5phly7q6wchdptjbktm2lx3wvujpcgvn2ca2jzu2vw2c6pn6zi"
  },
  {
    "tokenId": 122,
    "name": "B2S Badge #122",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihbzx7qo3uo3e6j47v46ptosdiybwqojpfjhcyfusmtr6gnmdmkmu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibq5rkotflpsszazetxaqvcrojmj2omiudcsbk5xysnji7qbbanei"
  },
  {
    "tokenId": 123,
    "name": "B2S Badge #123",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiflxouqlhz7uqdgi5qajiqu5lnsvtyf5n5wid242odyhiq5y72cdq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiabebkzm6tgtfzoz7nwrufmjqerkrvv5oqo5losmbkc6q7w5y5yr4"
  },
  {
    "tokenId": 126,
    "name": "B2S Badge #126",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiea6g6gqhy3tcdnoykrxu3z2d2xft2omscy7at3zbhejc7xigixti",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihqlwunxdvohasq4t22ydykb6ndvgmtbm5crew7l2ov66auw6wu3u"
  },
  {
    "tokenId": 124,
    "name": "B2S Badge #124",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigxzmnp2yopygrmw5ukx2apiiwj4na2wv2wzbveg4dvf4ql7css2e",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreie3z2uwfdsy5nre6fgulbyin62fdi3sdhvikux5z5fsbcbhhafpwa"
  },
  {
    "tokenId": 125,
    "name": "B2S Badge #125",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreic4jd7zalpcb5r6qkcat5ddo3hjvqipfw4efy7yxthbl3dvola7ua",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidmaeksw2nmcfqjhnlpnjt6x3edx7rdjd6kyq7fnbbv6svqxd3cju"
  },
  {
    "tokenId": 129,
    "name": "B2S Badge #129",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifiicarxush2npahjhn2lh5w7vva77okjisxuxkebmlzn4ng42k6a",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihsxl24w7ywidp7fsc3z66zpzuvbpyobkwqxk7fqgxhcern4m7iye"
  },
  {
    "tokenId": 128,
    "name": "B2S Badge #128",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiegqignwynrtrsy46zpaf7mfdupdi24c2sg3ailawo2e27ew2aeda",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid6m7egdg7neba2v4smtvjufftqpocno56yn7n4tococrhpn4eham"
  },
  {
    "tokenId": 127,
    "name": "B2S Badge #127",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihaofbcy2oxgvquimd2bsa6evb2xtrdqpoi3w5cpjd6fd44ymko5q",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreig2gaqbgowbub3y4lrufdbf2tiave4xz7ws6e75co2muik6asx5te"
  },
  {
    "tokenId": 130,
    "name": "B2S Badge #130",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigmyiwiegxicwn2ir6cgjunzkm3sugtofpzrw2kzmyaaqjfz5npzm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidy2uikmdhkp45bbutivgpqpr5cwjgkc6i3xt4d54jzvsweiuyz3e"
  },
  {
    "tokenId": 132,
    "name": "B2S Badge #132",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiap5lmspcy4e6ihaougbbfwgudn2aaesg7oc2c23fobhsiptlerd4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifjxnjg3ulcq2tsucddtmkq6ihymjz35dgumjjpqlsasjjaio5dmm"
  },
  {
    "tokenId": 131,
    "name": "B2S Badge #131",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibo356g6ni7ghqpowzyqabfgikilhxdgwh673npzd2z6pne2c2z3i",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiayatp6ux5d4n73j534qajc3pjl365wd3bcicyfe4y6a5fkhkwagu"
  },
  {
    "tokenId": 135,
    "name": "B2S Badge #135",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidhonbxikxpqhnpr3i7uuuvmczzx3m5apvstzq2e7ntxgu7ska7ri",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifn2g5n7lp6vdohzmc7n4ov656dhjriyoj6hmg77d7g4yjcgm6b3e"
  },
  {
    "tokenId": 134,
    "name": "B2S Badge #134",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreic66x32xmryvkikuvphu6h5by3ilxh7b3aj6ev2o4qgnz3yiqvtee",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidomsmooppql57eekamofdbumngojqmb77kujg76atajqhybsm6cm"
  },
  {
    "tokenId": 133,
    "name": "B2S Badge #133",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidyofifq3mhia3u2xw4u6lqrf3fht5p2ttaxr2id3q6ecec7mhnnu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiftyt2c5zoabkvtiv5l2eqamaprkff36bbqfnlmn7b6mknacxe6xy"
  },
  {
    "tokenId": 136,
    "name": "B2S Badge #136",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibi4tqd5lasoyr5nu6tfuygc5uq4v3rp3xlhi7i2rxxfezxxgve5q",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreic4jirgohxrqispm7q337lh4tsm3mbkoo7zdaupcncppokrhqo2by"
  },
  {
    "tokenId": 137,
    "name": "B2S Badge #137",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieikphwbxhzaphsz6yx2fd3xjjmpsycojtz73vrdn5d4pb5tt32sa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihswsqqy3b2fj5kn4bonsv4zwccsm6fvlpr5ey33vh57bxc2hjcmm"
  },
  {
    "tokenId": 138,
    "name": "B2S Badge #138",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiadex3aeanmjy5vwqacul36kfdwoylxloabrwcoza5lw4zhgasnaq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibs3n3yw3appmbcxhz5yuewma7x3w7hx7qw7nbwalo2pm4a57z2zi"
  },
  {
    "tokenId": 141,
    "name": "B2S Badge #141",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiatdxroum7jlluvsu6wlcg5zg6y7axfqojxrhmfpjgwcfzmz3jmk4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigdqme3ceiodn3xc5dqkqe6mos5baa3uu54x5dimxjh6pwcmlexza"
  },
  {
    "tokenId": 139,
    "name": "B2S Badge #139",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreigkyt5gafiubzuiolqf6iunmgdw7qvr63wlrzckcgblo4i4fdpcni",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifrm35x6ibtltv6a2wr2sehbgbnt43vclb22xle2yuv6utjltwktu"
  },
  {
    "tokenId": 140,
    "name": "B2S Badge #140",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreig6chosaspu42uhzsrecdm257hibmrerzfzvvh63ue3mr6mkunz5y",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifqk6aag25fffcmgz4txqci2q6iqngj4sdexot4gpaqq6d35hbgii"
  },
  {
    "tokenId": 143,
    "name": "B2S Badge #143",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieepq447hem4znszxbrvdzyfeno57wyc2szktogkjujpicfc5ywsa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreifmhwxkko7myt6l72owthvsaao5bp2l55v7szvhwyyedqeirq7svu"
  },
  {
    "tokenId": 142,
    "name": "B2S Badge #142",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihjf4bcbbio45bzk532va47mmuxomo2kc4dalf2nng4kivoaax7wu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreih6p56neh3vxqn3ry2zqrxf3brqv5u2plgmkmscpgibbtxnvewuby"
  },
  {
    "tokenId": 144,
    "name": "B2S Badge #144",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreid7tjo4t4xrhsheargfbp73zn3j35tk3mantztxlwov3iax6mf2u4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreieacw2clauwasjefhhxrn5hj5skvugetsmxvtkis7u4hfysxoqz2e"
  },
  {
    "tokenId": 147,
    "name": "B2S Badge #147",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreic26c2v5akz4isvil6semxxcphe5mytq3wdy3hxuf5fwe7n4xwyfq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidqloklwjphszx3x2s4knfg5bgiam3kwqqnlnqda3sm25pk4orau4"
  },
  {
    "tokenId": 145,
    "name": "B2S Badge #145",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidlg3d5mlquwqy4i3lzav2nv63md4ppyky3y2b2fyffwfpboxppxm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreib75z26dreew35dyr37gy4fqhtlkfbfhmrq56tthdd4qyxho6l7ju"
  },
  {
    "tokenId": 146,
    "name": "B2S Badge #146",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreif4k4itvf6ilooilxeysnacgl66hhrqc3anlkbq5uza4p3fovtchi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicqxnomlfv53xmwfy2wvj2tbkdhd6hap3445mune4du4ucoz4oxza"
  },
  {
    "tokenId": 148,
    "name": "B2S Badge #148",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibpxnxnyzweh37u63lv6zvgtnejsdkxp4dtp6emrlngzfk75vl2w4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiblkmvxmawassqtbsgfsazmhi7vbo7zsdjuter46i27qrcsogna5a"
  },
  {
    "tokenId": 150,
    "name": "B2S Badge #150",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiebkhqy7coq2q4onitrm6pffk3j7escgwmd2yoyftufmbam7gzvem",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreig7p5kt5msjljfaddiaivrht2c3prhcemvzgqrp6b35uczjxl3ww4"
  },
  {
    "tokenId": 151,
    "name": "B2S Badge #151",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiegrpzkge6jsz2ttwh76j36l5gecctvdsjw7uqf744tvly3gostzm",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidp77bwwsa6rufc4ob232uixdz7vedrq7kdvltbwal2yj4eyi63ju"
  },
  {
    "tokenId": 153,
    "name": "B2S Badge #153",
    "trait": "Red Team",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiffg35cpxvv2yqyc2y3l54vpkmmzmilmvkayzwditcsr7cgwbw57y",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreicf6pxcsk6pce5jajxrtgjjqj573fhbjgut3bsh2aybp75plytj34"
  },
  {
    "tokenId": 154,
    "name": "B2S Badge #154",
    "trait": "CTF Champion",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidhypp5f2c4sfoymvrjmrkvbducgoeurdlto5rdd5ptilnd6ze3ma",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreigw4onhqdcgoi7cnikul2ayxsgldpjrn3i42ed2f46j4wf3u73uzy"
  },
  {
    "tokenId": 155,
    "name": "B2S Badge #155",
    "trait": "Zero-Day Hunter",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreib6gz5sh5geqvj3ipovcacgsfxekkc3z6l44wuylqfmp4d5fzrbey",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihu6bk446imzf7bcqaqbzkvjzg7ovvxutefvvnwpurma74gdadihq"
  },
  {
    "tokenId": 156,
    "name": "B2S Badge #156",
    "trait": "Crypto Breaker",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreib4ogo2zvfanzog3ej32h4ja6hihmypk7g5h72bsqhtrzzpvie4xa",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibvkcdm2j666uapc7vxnoa37t72eg4p2uiibtul3tjb2zu4ywlbky"
  },
  {
    "tokenId": 158,
    "name": "B2S Badge #158",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicmxsc27k2l5ps2s4sqqw3kbdzf5kkukigld5ykkigadggpzo35x4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreiaddfvzycflzoyxtlh2qmw7zzy26twnhxsqycbzzsmv5hxhlwykey"
  },
  {
    "tokenId": 159,
    "name": "B2S Badge #159",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifrd7ylxlerdomlb7g2f3hu2k6orleu5ggzzbabnmmooa3xpoq3yi",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreic2lmfv5hqscn3yuyxjw5iw3iiaitfrpubkpcc3ir7354bribrejm"
  },
  {
    "tokenId": 157,
    "name": "B2S Badge #157",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibmsxo5keewxu6kst7ot3hfqdsncniribl5r5srqoasuqstogwkby",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidqp5hfwqt3advcc5nle6pi424nqq6uv6zereqla7dfsno3aobyea"
  },
  {
    "tokenId": 160,
    "name": "B2S Badge #160",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreiefa6licv7hgytvqbru6lajwo3dssvu5j4sl5rdphiffv53eyyrrq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreic3cpmca5qinytdy2hxzms5jbdnhv2j6uqsibvopqptxkrrkow27y"
  },
  {
    "tokenId": 162,
    "name": "B2S Badge #162",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreif6qeqym6wjk7mh5wqicpncbfmenpsu3v5c66txkaao34ydoqjkni",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihkfey3vbzq75aruhdcgzujirocdu7lokdcfojhqvxokr53ysr6ay"
  },
  {
    "tokenId": 161,
    "name": "B2S Badge #161",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreid7q3lha2al3pfralahiwglysyptvxnrp2t3vffs4tgu6q4t2g2r4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid4moyr6xkfwzg7t27xtx5wknvcdb6iqw7k35mck2ojqojznxihuy"
  },
  {
    "tokenId": 163,
    "name": "B2S Badge #163",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihrlfr4nzeclsvvrm36dww72oz2kucgd37nkxpgewokzlvrj3r6gq",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreihtuogwf325orwd3rednda43uwmce6tnnl6rzt3f27hrgzywsinwu"
  },
  {
    "tokenId": 165,
    "name": "B2S Badge #165",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "rare",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreihgatjo3enoncaneps24spqexebpkdx7abuhojvgbfkuwwqxc75ua",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreid42kmw4rmxa5sgxw7l7bndmfyopxulecwcnfabaw4xqujzeyscfu"
  },
  {
    "tokenId": 164,
    "name": "B2S Badge #164",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "uncommon",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreidyxtjylx7x5khxqz4p5jctvff45pn344hihnulhekt4qvlu5srue",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidts32rwrbjl35cekar7gyzm6v2ijmzxbisivekt2fcjjfuibzwbi"
  },
  {
    "tokenId": 167,
    "name": "B2S Badge #167",
    "trait": "Pen Tester",
    "style": "infosec",
    "rarity": "epic",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreicczp74ezgkwpfi5r7bvhpyflzlj4rjme2pofq7go2ot43fdukmum",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidzhxf5ukllzfhl5fs4uyanryxcpflastaoa2l2spvzevrjcj2k5i"
  },
  {
    "tokenId": 168,
    "name": "B2S Badge #168",
    "trait": "Rootkit Dev",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreibyehz2koopyun7v2muzxy4ljegfcfygf2sgiwytk7hr374zbo5c4",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreick4ccotffovzaqi7b265tmf56e7irdzj44ihkqtwc4raxubvjkpy"
  },
  {
    "tokenId": 169,
    "name": "B2S Badge #169",
    "trait": "OSINT Master",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreifjyv4bltlkv22fvri4aqjt4t7p2qbzkekp5tmyga45ebl5jpuxme",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreibyktlp76zoqvyy7mrguckhpjysv54xck3ibis53zx7lcaauhejbe"
  },
  {
    "tokenId": 170,
    "name": "B2S Badge #170",
    "trait": "Bug Bounty",
    "style": "infosec",
    "rarity": "common",
    "imageUrl": "https://gateway.pinata.cloud/ipfs/bafkreieloem7viiiwhpeebzbo3lahwh4wbo5fgpdigkqhioghprg4zjrmu",
    "metadataUrl": "https://gateway.pinata.cloud/ipfs/bafkreidg7axu3koqvn7sttmpvp6ot664bcai57t4unk26booe6iihlrc2a"
  }
]
